### ISSUE TITLE
Putty-Portable deletes all registry data for Putty and doesn't create the .ini file

### ISSUE THREAD

**Issue by stevenwhitej** [crazy-max/putty-portable#1]
I placed the portable files in my Putty folder, executed the putty-portable.bat file, then ran Putty.  At that point Putty contained the same sessions I'd saved into the registry.  I closed Putty and noticed there was no .ini file created.  So when I reopened Putty (with or without first running putty-portable.bat), there is no data present in Putty anymore, and my registry data has been erased.

This is beyond disappointing.

**Comment by Untitled-Document-1** [comment]
Sorry to here your situation. IMHO, there are better solutions out there. The one that I've used is http://jakub.kotrla.net/putty/.

You might already know this, but you should be able to restore your PuTTY sessions by opening an old copy of the registry hive, exporting the relevant key, and then importing it back into your current registry. Maybe this will help: https://www.howtogeek.com/howto/31136/how-to-restore-previous-versions-of-the-registry-in-windows-7/

**Comment by stevenwhitej** [comment]
Thanks, unfortunately I didn't have a backup exactly, but the sessions I needed weren't too hard to rebuild based on other info I had saved.

I just found another alternative as well - [http://download.cnet.com/PuTTY-Portable/3000-2155_4-10316746.html](url) - and it seems to work similarly to the way I expected this solution we're commenting on here.  Basically it virtualizes the registry key for Putty to a .reg file it keeps in its own folder.

**Comment by crazy-max** [comment]
@stevenwhitej This is an old project and i suggest you to switch to KiTTY Portable : http://portableapps.com/apps/internet/kitty-portable

**Comment by crazy-max** [comment]
But it still works for me (Windows 10 Pro) :

![image2](https://cloud.githubusercontent.com/assets/1951866/23642358/5e1075f4-02fa-11e7-92de-2f9cd325b7cc.png)

![image4](https://cloud.githubusercontent.com/assets/1951866/23642359/600c6b24-02fa-11e7-903f-9acf131b7215.png)

**Comment by stevenwhitej** [comment]
Thanks for the KiTTY suggestion.  I will check that out.  Honestly, after having my registry data deleted, I am probably not going to investigate/t-shoot that tool further.

**Comment by crazy-max** [comment]
No problem i understand
